#!/bin/bash
# Copyright (c) 2026 Aditya Shirsatrao. All rights reserved.
# Proprietary — see LICENSE file. No copying, cloning, or distribution.
# Auto-validate UI design before committing
make validate-ui
